# Multi-Cloud Edge Telemetry & Analytical Lakehouse
# Bridge: Terraform State to Ansible Inventory Generation

# 1. Dynamic Ansible Inventory File
resource "local_file" "ansible_dynamic_inventory" {
  filename = "${path.module}/../ansible/inventory/hosts.ini"
  content = templatefile("${path.module}/templates/hosts.ini.tftpl", {
    edge_gateways = var.factory_edge_gateways
  })
  file_permission = "0644"
}

# 2. Dynamic Ansible Runtime Metadata
resource "local_file" "ansible_lakehouse_endpoints" {
  filename = "${path.module}/../ansible/inventory/group_vars/terraform_endpoints.yml"
  content = <<-EOT
---
# Auto-generated by Terraform: Cloud Lakehouse Ingress Endpoints
terraform_kinesis_stream_name: "${aws_kinesis_stream.edge_telemetry_stream.name}"
terraform_kinesis_stream_arn: "${aws_kinesis_stream.edge_telemetry_stream.arn}"
terraform_bronze_bucket: "${aws_s3_bucket.bronze_raw_lakehouse.id}"
terraform_silver_bucket: "${aws_s3_bucket.silver_cleansed_lakehouse.id}"
terraform_gold_bucket: "${aws_s3_bucket.gold_aggregated_lakehouse.id}"
terraform_quarantine_bucket: "${aws_s3_bucket.quarantine_dead_letter.id}"
terraform_deployment_timestamp: "${timestamp()}"
EOT
  file_permission = "0644"
}
